### ISSUE TITLE
Keras TypeError: 'list' object is not an iterator

### ISSUE THREAD

**Issue by dizcza** [Tobias-Fischer/rt_gene#127]
Hello, I'm trying to run the minimalistic example, rt_gene_standalone, and I'm getting errors

```python
Traceback (most recent call last):
  File "/home/dizcza/PycharmProjects/other/rt_gene/rt_gene_standalone/estimate_gaze_standalone.py", line 211, in <module>
    estimate_gaze(image_file_name, image, _dist_coefficients, _camera_matrix)
  File "/home/dizcza/PycharmProjects/other/rt_gene/rt_gene_standalone/estimate_gaze_standalone.py", line 104, in estimate_gaze
    gaze_est = gaze_estimator.estimate_gaze_twoeyes(inference_input_left_list=input_l_list,
  File "/home/dizcza/PycharmProjects/other/rt_gene/rt_gene_standalone/rt_gene/estimate_gaze_tensorflow.py", line 64, in estimate_gaze_twoeyes
    mean_prediction = self.ensemble_model.predict({'img_input_L': np.array(inference_input_left_list),
  File "/home/dizcza/miniconda3/envs/rt_gene/lib/python3.10/site-packages/keras/engine/training_v1.py", line 1058, in predict
    return func.predict(
  File "/home/dizcza/miniconda3/envs/rt_gene/lib/python3.10/site-packages/keras/engine/training_arrays_v1.py", line 801, in predict
    return predict_loop(
  File "/home/dizcza/miniconda3/envs/rt_gene/lib/python3.10/site-packages/keras/engine/training_arrays_v1.py", line 419, in model_iteration
    batch_outs = f(ins_batch)
  File "/home/dizcza/miniconda3/envs/rt_gene/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_fileow_yq__g.py", line 15, in tf__predict_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
  File "/home/dizcza/miniconda3/envs/rt_gene/lib/python3.10/site-packages/keras/engine/training.py", line 2026, in step_function
    data = next(iterator)
TypeError: in user code:

    File "/home/dizcza/miniconda3/envs/rt_gene/lib/python3.10/site-packages/keras/engine/training.py", line 2041, in predict_function  *
        return step_function(self, iterator)
    File "/home/dizcza/miniconda3/envs/rt_gene/lib/python3.10/site-packages/keras/engine/training.py", line 2026, in step_function  **
        data = next(iterator)

    TypeError: 'list' object is not an iterator
```

The exception happens in the keras traning.py `step_function()`:

```python
        def step_function(model, iterator):
            """Runs a single evaluation step."""

            def run_step(data):
                outputs = model.predict_step(data)
                # Ensure counter is updated only if `test_step` succeeds.
                with tf.control_dependencies(_minimum_control_deps(outputs)):
                    model._predict_counter.assign_add(1)
                return outputs

            if self._jit_compile:
                run_step = tf.function(
                    run_step, jit_compile=True, reduce_retracing=True
                )

            data = next(iterator)
            outputs = model.distribute_strategy.run(run_step, args=(data,))
            outputs = reduce_per_replica(
                outputs, self.distribute_strategy, reduction="concat"
            )
            return outputs
```

tensorflow 2.10.0, CPU only.

If I use the latest tensorflor 2.17, I get another error also in keras.

I was also getting errors with sessions so I commented them out:

```diff
diff --git a/rt_gene/src/rt_gene/estimate_gaze_tensorflow.py b/rt_gene/src/rt_gene/estimate_gaze_tensorflow.py
index f3e6455..886a63b 100644
--- a/rt_gene/src/rt_gene/estimate_gaze_tensorflow.py
+++ b/rt_gene/src/rt_gene/estimate_gaze_tensorflow.py
@@ -24,8 +24,9 @@ class GazeEstimator(GazeEstimatorBase):
                 config.gpu_options.allow_growth = True
                 config.gpu_options.per_process_gpu_memory_fraction = 0.3
             config.log_device_placement = False
-            self.sess = tf.compat.v1.Session(config=config)
-            tf.compat.v1.keras.backend.set_session(self.sess)
+            self.sess = None
+            # self.sess = tf.compat.v1.Session(config=config)
+            # tf.compat.v1.keras.backend.set_session(self.sess)
 
         models = []
         img_input_l = tf.keras.Input(shape=(36, 60, 3), name='img_input_L')
@@ -47,7 +48,7 @@ class GazeEstimator(GazeEstimatorBase):
         else:
             raise ValueError("No models were loaded")
         # noinspection PyProtectedMember
-        self.ensemble_model._make_predict_function()
+        self.ensemble_model.make_predict_function()
 
         tqdm.write('Loaded ' + str(len(models)) + ' model(s)')
 
@@ -59,7 +60,7 @@ class GazeEstimator(GazeEstimatorBase):
 
     def estimate_gaze_twoeyes(self, inference_input_left_list, inference_input_right_list, inference_headpose_list):
         with self.graph.as_default():
-            tf.compat.v1.keras.backend.set_session(self.sess)
+            # tf.compat.v1.keras.backend.set_session(self.sess)
             mean_prediction = self.ensemble_model.predict({'img_input_L': np.array(inference_input_left_list),
                                                            'img_input_R': np.array(inference_input_right_list),
                                                            'headpose_input': np.array(inference_headpose_list)})
```

Feedback much appreciated.

**Comment by Tobias-Fischer** [comment]
Can you just set `--gaze_backend pytorch` to avoid using tensorflow? I think you'd need to go back to a quite-a-bit-older version of tensorflow; they must have changed something in the API.

**Comment by dizcza** [comment]
It works thanks! I needed to select another model and I chose `gaze_model_pytorch_vgg16_prl_mpii_allsubjects1.model` though I don't know what it corresponds to

> To use an ensemble scheme using 4 models trained on the MPII, UTMV and RT-GENE datasets, simply use the --models argument

There are 4 models and only 3 datasets.

Anyhow, I rewrote the script to use a webcam for the demo - having such a demo scenario would really help beginners - and the gaze estimate vectors are quite well...

**Comment by Tobias-Fischer** [comment]
Would you be willing to contribute the rewritten script as a pull request?
