### ISSUE TITLE
Estimate_gaze.launch

### ISSUE THREAD

**Issue by godfreylui** [Tobias-Fischer/rt_gene#28]
Hi Tobias

I am only using a webcam is there any other things I need to change in my estimate_gaze.launch file? I continue to get this message with the bold text in red when I run the the file. I also had trouble (memory error) installing the torch modules ie torch torchvision face-alignment due to the lack of ram I think, and hence downloaded them with no cache like so pip --no-cache-dir install face-alignment, so not sure if that is also a reason. Thank you

Best wishes,

Godfrey

Traceback (most recent call last):
  File "/home/godfrey/wheelchair/src/rt_gene/rt_gene/scripts/extract_landmarks_node.py", line 19, in <module>
    landmark_extractor = rt_gene.extract_landmarks_method.LandmarkMethod()
  File "/home/godfrey/wheelchair/src/rt_gene/rt_gene/src/rt_gene/extract_landmarks_method.py", line 118, in __init__
    self.face_net = FaceDetector(device=self.device_id_facedetection)
  File "/home/godfrey/.local/lib/python2.7/site-packages/face_alignment/detection/sfd/sfd_detector.py", line 39, in __init__
    os.path.join(path_to_temp_detector))
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 249, in retrieve
    tfp = open(filename, 'wb')
IOError: [Errno 2] No such file or directory: '/home/godfrey/.face_alignment/data/s3fd_convert.pth.download'
2019-06-30 16:13:57.814582: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-30 16:13:57.818264: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2699870000 Hz
2019-06-30 16:13:57.818466: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5641d151a150 executing computations on platform Host. Devices:
2019-06-30 16:13:57.818503: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
Load model model_nets/Model_allsubjects1.h5

**[gaze/extract_landmarks_new-2] process has died [pid 8301, exit code 1, cmd /home/godfrey/wheelchair/src/rt_gene/rt_gene/scripts/extract_landmarks_node.py /camera_info:=/kinect2/hd/camera_info /image:=/kinect2/hd/image_color_rect __name:=extract_landmarks_new __log:=/home/godfrey/.ros/log/a9d158b6-9b49-11e9-8a16-c4b301d0eb11/gaze-extract_landmarks_new-2.log].
log file: /home/godfrey/.ros/log/a9d158b6-9b49-11e9-8a16-c4b301d0eb11/gaze-extract_landmarks_new-2*.log**

2019-06-30 16:13:58.874737: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
/home/godfrey/.local/lib/python2.7/site-packages/keras/engine/saving.py:327: UserWarning: Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
  warnings.warn('Error in loading the saved optimizer '

**Comment by Tobias-Fischer** [comment]
Hi, download these files and save them into `~/.face_alignment/data`:

```
https://www.adrianbulat.com/downloads/python-fan/2DFAN-4.pth.tar
https://www.adrianbulat.com/downloads/python-fan/3DFAN-4.pth.tar
https://www.adrianbulat.com/downloads/python-fan/depth.pth.tar
https://www.adrianbulat.com/downloads/python-fan/s3fd_convert.pth
```

PS: It seems like your computer is really slow, low in memory and does not have a GPU. You will run into all kinds of problems (like this issue) and I would highly recommend using another computer.
